name: DiCyR
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.7
    - pip
    - pytorch
    - torchvision==0.6.1
    - numpy
    - pyyaml=3.12
    - scikit-learn
    - matplotlib
    - h5py
    - tqdm
    - jupyterlab
    - pip:
        - tensorboard
